
path: C:\Users\sebas\Documents\GitHub\train-yolov8-custom-dataset-step-by-step-guide\Face Detection.v18-yolov8.yolov8  # dataset root dir
train: train  # train images (relative to 'path')
val: valid  # val images (relative to 'path')

# Classes
names:
  0: alpaca
